all:	evtmlib.o

evlib.o:	../evlib/evlib.c	../evlib/evlib.h
	echo "compilation de evlib."
	cc -c evlib.c

timerlib.o:	../timerlib/timerlib.c	../timerlib/timerlib.h
	echo "compilation de timerlib."
	cc -c timerlib.c

evtmlib.o:	evtmlib.c	evtmlib.h
	echo "compilation de evtmlib."
	cc -c evtmlib.c
