-- Raphael Javaux - 2202

CREATE TABLE BaremeMinMaxJavauxra (
  NUMDEP VARCHAR2(6)
    CONSTRAINT PK_BAREMEMINMAX PRIMARY KEY
    CONSTRAINT FK_BAREMEMINMAX_DEPARTEMENTS REFERENCES DEPARTEMENTS(NUMDEP),
  BAREMEMIN NUMBER NOT NULL,
  BAREMEMAX NUMBER NOT NULL
);

INSERT INTO BaremeMinMaxJavauxra
  SELECT D.NUMDEP, 
    COALESCE(min(E.BAREME), (SELECT min(E.BAREME)
      FROM EMPLOYES E)
    ),
    COALESCE(max(E.BAREME), (SELECT max(E.BAREME)
      FROM EMPLOYES E)
    )
  FROM DEPARTEMENTS D
  LEFT JOIN EMPLOYES E
    ON E.NUMDEP = D.NUMDEP
  GROUP BY D.NUMDEP
  ORDER BY D.NUMDEP -- Ordre de l'ennoncé 
;

create or replace
TRIGGER EMPLOYEBAREMEJAVAUXRA 
BEFORE INSERT OR UPDATE OF BAREME,NUMDEP ON EMPLOYES
FOR EACH ROW
DECLARE
  DansDepartements NUMBER;
  BaremeMin NUMBER;
  BaremeMax NUMBER;
BEGIN
  IF :NEW.NUMDEP IS NULL THEN
    :NEW.NUMDEP := 'd00005';
    
    SELECT BAREMEMIN INTO :NEW.BAREME
    FROM BAREMEMINMAXJAVAUXRA
    WHERE NUMDEP = :NEW.NUMDEP;
  ELSE
    SELECT COUNT(*) INTO DansDepartements
    FROM DEPARTEMENTS D
    WHERE D.NUMDEP = :NEW.NUMDEP;
    
    IF DansDepartements <> 1 THEN
      :NEW.NUMDEP := 'd00005';
      
      SELECT BAREMEMIN INTO :NEW.BAREME
      FROM BAREMEMINMAXJAVAUXRA
      WHERE NUMDEP = :NEW.NUMDEP;
    ELSE
      IF :NEW.BAREME IS NOT NULL THEN
        SELECT BAREMEMIN INTO BaremeMin
        FROM BAREMEMINMAXJAVAUXRA
        WHERE NUMDEP = :NEW.NUMDEP;
        
        SELECT BAREMEMAX INTO BaremeMax
        FROM BAREMEMINMAXJAVAUXRA
        WHERE NUMDEP = :NEW.NUMDEP;
        
        IF :NEW.BAREME < BaremeMin OR :NEW.BAREME > BaremeMax THEN
          SELECT BAREMEMIN INTO :NEW.BAREME
          FROM BAREMEMINMAXJAVAUXRA
          WHERE NUMDEP = :NEW.NUMDEP;
        END IF;
      END IF;
    END IF;
  END IF;
END;

-- TESTS
UPDATE EMPLOYES SET NUMDEP = 'd00002' WHERE NUMSECU = 123456;
--> Bareme à 69000 et numdep à d00002
UPDATE EMPLOYES SET BAREME = 5000 WHERE NUMSECU = 123456;
--> Bareme à 65000 (minimum de d00002)
UPDATE EMPLOYES SET BAREME = 99999 WHERE NUMSECU = 123456;
--> Bareme à 65000 (minimum de d00002)
UPDATE EMPLOYES SET BAREME = NULL WHERE NUMSECU = 123456;
--> Bareme à NULL
UPDATE EMPLOYES SET NUMDEP = NULL WHERE NUMSECU = 123456;
--> Numdep à d00005 et bareme à 5400
UPDATE EMPLOYES SET NUMDEP = 'cafet' WHERE NUMSECU = 123456;
--> Numdep à d00005 et bareme à 5400
