SELECT REFGROUPE
FROM PARCOURS_HE
WHERE MATRICULE = (SELECT MATRICULE
  FROM ETUDIANTS
  WHERE UPPER(NOM) = 'HUBERT'
    AND UPPER(PRENOM) = 'CECILE')
  AND ANSCO = 2007
  AND ANNETUD = 2
  AND REFFORMDET = 'TECH-GRAI';

UPDATE PARCOURS_HE
SET REFGROUPE = (SELECT P.REFGROUPE
  FROM PARCOURS_HE P
  INNER JOIN ETUDIANTS E
    ON E.MATRICULE = P.MATRICULE
  WHERE E.SEXE = 'F'
    AND P.ANSCO = 2007
    AND P.ANNETUD = 2
    AND P.REFFORMDET = 'TECH-GRAI'
  GROUP BY P.REFGROUPE
  HAVING COUNT(*) = (SELECT MAX(COUNT(*))
    FROM PARCOURS_HE P
    INNER JOIN ETUDIANTS E
      ON E.MATRICULE = P.MATRICULE
    WHERE E.SEXE = 'F'
      AND P.ANSCO = 2007
      AND P.ANNETUD = 2
      AND P.REFFORMDET = 'TECH-GRAI'
    GROUP BY P.REFGROUPE)
  )
WHERE MATRICULE = (SELECT MATRICULE
  FROM ETUDIANTS
  WHERE UPPER(NOM) = 'HUBERT'
    AND UPPER(PRENOM) = 'CECILE')

  AND ANSCO = 2007;
 
SELECT REFGROUPE
FROM PARCOURS_HE
WHERE MATRICULE = (SELECT MATRICULE
  FROM ETUDIANTS
  WHERE UPPER(NOM) = 'HUBERT'
    AND UPPER(PRENOM) = 'CECILE')
  AND ANSCO = 2007
  AND ANNETUD = 2
  AND REFFORMDET = 'TECH-GRAI';

ROLLBACK;
