CREATE USER &1 IDENTIFIED BY &1	
DEFAULT TABLESPACE USERS 
TEMPORARY TABLESPACE TEMP 	
PROFILE DEFAULT ACCOUNT UNLOCK;
GRANT CONNECT TO &1;
GRANT RESOURCE TO &1;
GRANT CREATE VIEW TO &1;
GRANT EXECUTE ON SYS.DBMS_LOCK TO &1;
ALTER USER &1 QUOTA 10M ON USERS;


