CREATE TABLE ErreursContraintes (adresse ROWID, utilisateur VARCHAR2(30),
  nomtable VARCHAR2(30), nomcontrainte VARCHAR2(30));
  
ALTER TABLE ETUDIANTS
ADD CONSTRAINT CK_ETUDIANTS_DATENAISSANCE
  CHECK (DATENAISSANCE < DATEENTREE)
EXCEPTIONS INTO ErreursContraintes;

ALTER TABLE ETUDIANTS
ADD CONSTRAINT CK_ETUDIANTS_DATEENTREE
  CHECK (MONTHS_BETWEEN(DATEENTREE, DATENAISSANCE) / 12 >= 17)
EXCEPTIONS INTO ErreursContraintes;

ALTER TABLE ETUDIANTS
ADD CONSTRAINT CK_ETUDIANTS_SEXE
  CHECK (SEXE IN ('F', 'M'))
EXCEPTIONS INTO ErreursContraintes;

ALTER TABLE ETUDIANTS
ADD CONSTRAINT CK_ETUDIANTS_ETATCIVIL
  CHECK (ETATCIVIL IN ('M', 'C') OR ETATCIVIL IS NULL)
EXCEPTIONS INTO ErreursContraintes;

ALTER TABLE ETUDIANTS
ADD CONSTRAINT CK_ETUDIANTS_SITUATION
  CHECK (SITUATION IN ('I', 'E', 'D') OR SITUATION IS NULL)
EXCEPTIONS INTO ErreursContraintes;
