/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AffichageLigne.java
 *
 * Created on 3 juin 2011, 18:57:14
 */
package inpresbus.ui;

import inpresbus.data.Ligne;
import inpresbus.data.Segment;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author rapha
 */
public class AffichageLigne extends javax.swing.JDialog {

    /** Creates new form AffichageLigne */
    public AffichageLigne(Ligne ligne, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.afficherLigne(ligne);
    }
    
    private void afficherLigne(Ligne ligne)
    {
        DefaultTreeModel mTree = (DefaultTreeModel) this.treeArrets.getModel();
        DefaultMutableTreeNode rootNode = (DefaultMutableTreeNode) mTree.getRoot();

        for (Segment seg : ligne.getSegments()) {
            DefaultMutableTreeNode arretNode = new DefaultMutableTreeNode(
                seg.getDepart()
                + " - " +
                seg.getArrivee()
            );
            DefaultMutableTreeNode distanceNode = new DefaultMutableTreeNode(
                seg.getDuree()
            );
            arretNode.add(distanceNode);
            rootNode.add(arretNode);
        }
            
        mTree.reload();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        treeArrets = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Affichage de la ligne");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Arrêts");
        treeArrets.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(treeArrets);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree treeArrets;
    // End of variables declaration//GEN-END:variables
}
