/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListesLigne.java
 *
 * Created on 2 juin 2011, 15:44:29
 */
package inpresbus.ui;

import inpresbus.data.Ligne;
import java.awt.Frame;
import javax.swing.DefaultListModel;

/**
 *
 * @author rapha
 */
public class ListeLignes extends javax.swing.JDialog {

    /** Creates new form ListesLigne */
    public ListeLignes(java.awt.Frame parent, boolean modal)
            throws Exception
    {
        super(parent, modal);
        initComponents();
        
        DefaultListModel model = (DefaultListModel) this.listLignes.getModel();
        
        for (String nomLigne : Ligne.dir.listerObjets()) {
            model.addElement((Object) nomLigne);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listLignes = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Liste des lignes");

        listLignes.setModel(new DefaultListModel());
        listLignes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listLignesMouseClicked(evt);
            }
        });
        listLignes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listLignesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listLignes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("CallToThreadDumpStack")
    private void listLignesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listLignesValueChanged

    }//GEN-LAST:event_listLignesValueChanged

    private void listLignesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listLignesMouseClicked
        try {
            Ligne ligne = (Ligne) Ligne.dir.chargerObjet(
                (String) this.listLignes.getSelectedValue()
            );
            
            new AffichageLigne(ligne, (Frame) this.getParent(), true).setVisible(true);
        } catch (Exception ex) {
           ex.printStackTrace();
        }
    }//GEN-LAST:event_listLignesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new ListeLignes(null, false).setVisible(true);
                } catch (Exception ex) {
                    System.out.println(
                        "Erreur lors de la création de la liste: " +
                        ex.getMessage()
                    );
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listLignes;
    // End of variables declaration//GEN-END:variables
}
