/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFormClient.java
 *
 * Created on 7 juin 2011, 21:18:43
 */
package inpresbus.ui;

import javax.swing.DefaultListModel;
import network.NetworkStringReceiver;

/**
 *
 * @author rapha
 */
public class MainFormVoyageurs extends javax.swing.JFrame {

    /** Creates new form MainFormClient */
    public MainFormVoyageurs(int port) {
        initComponents();
        
        new NetworkStringReceiver(port, this.listHoraires);
    }
    
    private void _chargerHoraires(String horaires)
    {
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listHoraires = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informations aux voyageurs");

        jLabel1.setFont(new java.awt.Font("Sans Serif", 0, 18)); // NOI18N
        jLabel1.setText("Informations aux voyageurs");

        listHoraires.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(listHoraires);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFormVoyageurs(5000).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listHoraires;
    // End of variables declaration//GEN-END:variables
}
