/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NouveauBus.java
 *
 * Created on 4 juin 2011, 13:20:59
 */
package inpresbus.ui;

import inpresbus.data.Bus;
import inpresbus.data.Dimensions3D;
import inpresbus.data.exceptions.BadDimensionsException;
import inpresbus.data.exceptions.BadIdentifierException;

/**
 *
 * @author rapha
 */
public class NouveauBus extends javax.swing.JDialog {

    /** Creates new form NouveauBus */
    public NouveauBus(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIdentifiant = new javax.swing.JLabel();
        labelLongueur = new javax.swing.JLabel();
        textLongueur = new javax.swing.JTextField();
        textLargeur = new javax.swing.JTextField();
        labelLargeur = new javax.swing.JLabel();
        textIdentifiant = new javax.swing.JTextField();
        textHauteur = new javax.swing.JTextField();
        labelHauteur = new javax.swing.JLabel();
        textPassagers = new javax.swing.JTextField();
        labelPassagers = new javax.swing.JLabel();
        checkArticule = new javax.swing.JCheckBox();
        checkEnService = new javax.swing.JCheckBox();
        labelDepot = new javax.swing.JLabel();
        textDepot = new javax.swing.JTextField();
        labelErreur = new javax.swing.JLabel();
        butEnregistrer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nouveau bus");

        labelIdentifiant.setText("Identifiant:");

        labelLongueur.setText("Longueur:");

        textLongueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLongueurActionPerformed(evt);
            }
        });

        textLargeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLargeurActionPerformed(evt);
            }
        });

        labelLargeur.setText("Largeur:");

        textIdentifiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdentifiantActionPerformed(evt);
            }
        });

        textHauteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHauteurActionPerformed(evt);
            }
        });

        labelHauteur.setText("Hauteur:");

        textPassagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPassagersActionPerformed(evt);
            }
        });

        labelPassagers.setText("Nombre de passagers:");

        checkArticule.setText("Articulé");
        checkArticule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkArticuleActionPerformed(evt);
            }
        });

        checkEnService.setText("En service");
        checkEnService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEnServiceActionPerformed(evt);
            }
        });

        labelDepot.setText("Dépot:");

        textDepot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDepotActionPerformed(evt);
            }
        });

        labelErreur.setFont(new java.awt.Font("Sans Serif", 1, 13)); // NOI18N
        labelErreur.setForeground(java.awt.Color.red);

        butEnregistrer.setText("Enregistrer");
        butEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEnregistrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkArticule)
                        .addGap(18, 18, 18)
                        .addComponent(checkEnService))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelErreur, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                        .addComponent(butEnregistrer))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLongueur)
                            .addComponent(labelPassagers)
                            .addComponent(labelIdentifiant))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textIdentifiant)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textLongueur, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelLargeur))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textPassagers, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelDepot)))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textLargeur, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelHauteur)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textHauteur, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(textDepot))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdentifiant)
                    .addComponent(textIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLongueur)
                    .addComponent(labelLargeur)
                    .addComponent(textLargeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLongueur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHauteur)
                    .addComponent(textHauteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassagers)
                    .addComponent(textPassagers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDepot)
                    .addComponent(textDepot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkArticule)
                    .addComponent(checkEnService))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelErreur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butEnregistrer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textLongueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLongueurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLongueurActionPerformed

    private void textLargeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLargeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLargeurActionPerformed

    private void textIdentifiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdentifiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdentifiantActionPerformed

    private void textHauteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHauteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHauteurActionPerformed

    private void textPassagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPassagersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPassagersActionPerformed

    private void checkArticuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkArticuleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkArticuleActionPerformed

    private void checkEnServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEnServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkEnServiceActionPerformed

    private void textDepotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDepotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDepotActionPerformed

    private void butEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEnregistrerActionPerformed
       try {            
            if (Bus.dir.objetExistant(this.textIdentifiant.getText())) {
                this.labelErreur.setText("L'identifiant du bus existe déjà");
            } else {
                Bus bus = new Bus(
                    this.textIdentifiant.getText(),
                    new Dimensions3D(
                        Float.parseFloat(this.textLongueur.getText()),
                        Float.parseFloat(this.textLargeur.getText()),
                        Float.parseFloat(this.textHauteur.getText())
                    ),
                    Integer.parseInt(this.textPassagers.getText()),
                    this.checkArticule.isSelected(),
                    this.checkEnService.isSelected(),
                    this.textDepot.getText()
                );

                Bus.dir.enregistrerObjet(bus, this.textIdentifiant.getText());
               
                this.dispose();
             }
        } catch (BadDimensionsException ex) {
            this.labelErreur.setText("Les dimensions ne sont pas valides");
        } catch (BadIdentifierException ex) {
            this.labelErreur.setText("L'identifiant n'est pas valide");
        } catch (Exception ex) {
            System.err.print("Erreur lors de l'enregistrement du bus");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_butEnregistrerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                NouveauBus dialog = new NouveauBus(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butEnregistrer;
    private javax.swing.JCheckBox checkArticule;
    private javax.swing.JCheckBox checkEnService;
    private javax.swing.JLabel labelDepot;
    private javax.swing.JLabel labelErreur;
    private javax.swing.JLabel labelHauteur;
    private javax.swing.JLabel labelIdentifiant;
    private javax.swing.JLabel labelLargeur;
    private javax.swing.JLabel labelLongueur;
    private javax.swing.JLabel labelPassagers;
    private javax.swing.JTextField textDepot;
    private javax.swing.JTextField textHauteur;
    private javax.swing.JTextField textIdentifiant;
    private javax.swing.JTextField textLargeur;
    private javax.swing.JTextField textLongueur;
    private javax.swing.JTextField textPassagers;
    // End of variables declaration//GEN-END:variables
}
