package inpresbus.ui;

import java.util.*;

import inpresbus.data.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class NouvelleLigne extends javax.swing.JDialog {
    
    // Etape 1
    private Ligne _ligne = null;
    
    // Etape 2
    private LinkedList<String> _arrets = new LinkedList<String>();
    
    // Etape 3
    private LinkedList<Float> _distances = new LinkedList<Float>();

    /** Creates new form MainUi */
    public NouvelleLigne(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
     
        this.setEtape1Enabled(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        labelNumLigne = new javax.swing.JLabel();
        textNumLigne = new javax.swing.JTextField();
        labelNouvelArret = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        textNomArret = new javax.swing.JTextField();
        butAjouter = new javax.swing.JButton();
        labelSupprimerArret = new javax.swing.JLabel();
        comboArrets = new javax.swing.JComboBox();
        butSupprimerArret = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableArrets = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        labelEtape1 = new javax.swing.JLabel();
        labelEtape2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        labelEtape3 = new javax.swing.JLabel();
        butConfirmerArrets = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        treeArrets = new javax.swing.JTree();
        labelDe = new javax.swing.JLabel();
        labelA = new javax.swing.JLabel();
        butArretSuivant = new javax.swing.JButton();
        labelDistance = new javax.swing.JLabel();
        textDistance = new javax.swing.JTextField();
        labelArret1 = new javax.swing.JLabel();
        labelArret2 = new javax.swing.JLabel();
        butCreer = new javax.swing.JButton();
        labelErreur = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nouvelle ligne");

        labelNumLigne.setText("Numero de la ligne :");

        textNumLigne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumLigneActionPerformed(evt);
            }
        });

        labelNouvelArret.setText("Nouvel arrêt :");

        textNomArret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomArretActionPerformed(evt);
            }
        });

        butAjouter.setText("Ajouter");
        butAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAjouterActionPerformed(evt);
            }
        });

        labelSupprimerArret.setText("Supprimer un arrêt :");

        butSupprimerArret.setText("Supprimer");
        butSupprimerArret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSupprimerArretActionPerformed(evt);
            }
        });

        tableArrets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Arret"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableArrets);

        labelEtape1.setText("Etape 1:");

        labelEtape2.setText("Etape 2:");

        labelEtape3.setText("Etape 3:");

        butConfirmerArrets.setText("Confirmer");
        butConfirmerArrets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butConfirmerArretsActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Arrêts");
        treeArrets.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(treeArrets);

        labelDe.setText("De: ");

        labelA.setText("A:");

        butArretSuivant.setText("Suivant");
        butArretSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butArretSuivantActionPerformed(evt);
            }
        });

        labelDistance.setText("Distance: ");

        textDistance.setText(" ");
        textDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDistanceActionPerformed(evt);
            }
        });

        labelArret1.setText(" ");

        labelArret2.setText(" ");

        butCreer.setText("Creer");
        butCreer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCreerActionPerformed(evt);
            }
        });

        labelErreur.setForeground(new java.awt.Color(204, 0, 0));
        labelErreur.setText("    ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNumLigne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNumLigne, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                        .addComponent(butCreer))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelErreur)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(labelEtape2))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(labelEtape1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butConfirmerArrets)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(labelEtape3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelDistance)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelDe)
                                            .addComponent(labelA))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelArret2)
                                            .addComponent(labelArret1))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butArretSuivant)
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(labelSupprimerArret)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboArrets, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(butSupprimerArret))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(labelNouvelArret)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textNomArret, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(butAjouter))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelEtape1)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNumLigne)
                            .addComponent(textNumLigne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butCreer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(labelEtape2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNouvelArret)
                            .addComponent(textNomArret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butAjouter))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSupprimerArret)
                            .addComponent(comboArrets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butSupprimerArret))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butConfirmerArrets))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(292, 292, 292)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelEtape3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDe)
                            .addComponent(labelArret1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelA)
                            .addComponent(labelArret2))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDistance)
                            .addComponent(textDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(butArretSuivant))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(labelErreur)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _setEtape1Enabled(boolean enabled)
    {
        this.labelEtape1.setEnabled(enabled);
        this.labelNumLigne.setEnabled(enabled);
        this.textNumLigne.setEnabled(enabled);
    }
    
    private void _setEtape2Enabled(boolean enabled)
    {
        this.labelEtape2.setEnabled(enabled);
        this.labelNouvelArret.setEnabled(enabled);
        this.textNomArret.setEnabled(enabled);
        this.butAjouter.setEnabled(enabled);
        this.labelSupprimerArret.setEnabled(enabled);
        this.comboArrets.setEnabled(enabled);
        this.butSupprimerArret.setEnabled(enabled);
        this.tableArrets.setEnabled(enabled);
        this.butConfirmerArrets.setEnabled(enabled);
    }
    
    private void _setEtape3Enabled(boolean enabled)
    {
        this.labelEtape3.setEnabled(enabled);
        this.labelDe.setEnabled(enabled);
        this.labelA.setEnabled(enabled);
        this.labelArret1.setEnabled(enabled);
        this.labelArret2.setEnabled(enabled);
        this.labelDistance.setEnabled(enabled);
        this.textDistance.setEnabled(enabled);
        this.treeArrets.setEnabled(enabled);
        this.butArretSuivant.setEnabled(enabled);
    }
    
    private void setEtape1Enabled(boolean enabled)
    {
        this._setEtape1Enabled(enabled);
        this._setEtape2Enabled(!enabled);
        this._setEtape3Enabled(!enabled);
    }
    
    private void setEtape2Enabled(boolean enabled)
    {
        this._setEtape1Enabled(!enabled);
        this._setEtape2Enabled(enabled);
        this._setEtape3Enabled(!enabled);
    }
    
    private void setEtape3Enabled(boolean enabled)
    {
        this._setEtape1Enabled(!enabled);
        this._setEtape2Enabled(!enabled);
        this._setEtape3Enabled(enabled);
    }
    
    private void textNumLigneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumLigneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumLigneActionPerformed

    private void textNomArretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomArretActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomArretActionPerformed

    private void butSupprimerArretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSupprimerArretActionPerformed
        if (this.comboArrets.getSelectedObjects().length > 0) {
            String nom = (String) this.comboArrets.getSelectedObjects()[0];
            int index = this._arrets.indexOf(nom);
            this._arrets.remove(index);
            
            DefaultTableModel mTable = (DefaultTableModel) this.tableArrets.getModel();
            mTable.removeRow(index);
            
            DefaultComboBoxModel mCombo = (DefaultComboBoxModel) this.comboArrets.getModel();
            mCombo.removeElementAt(index);
        } else {
            this.setError("Aucun arrêt à supprimer");
        }
    }//GEN-LAST:event_butSupprimerArretActionPerformed

    private void butConfirmerArretsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butConfirmerArretsActionPerformed
        if (this._arrets.size() >= 2) {
            this.setEtape3Enabled(true);
            this.labelArret1.setText(this._arrets.get(0));
            this.labelArret2.setText(this._arrets.get(1));
            
            if (this._arrets.size() < 3)
                this.butArretSuivant.setText("Confirmer");
            else
                this.butArretSuivant.setText("Suivant");
        } else {
            this.setError("Vous devez au moins entrer deux arrêts");
        }
    }//GEN-LAST:event_butConfirmerArretsActionPerformed

    private void butArretSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butArretSuivantActionPerformed
        try {
            this._distances.add(Float.parseFloat(this.textDistance.getText()));
        } catch (NumberFormatException e) {
            this.setError("Distance non valide");
            
            return;
        }
        
        if (this._distances.size() == this._arrets.size() - 1) {
            // Dernier arret, enregistre les arrets et quitte la fenêtre
            
            Segment[] segments = new Segment[this._distances.size()];
            
            int i = 0;
            for (float distance : this._distances) {
                segments[i] = new Segment(
                        this._arrets.get(i), this._arrets.get(i+1),
                        distance
                );
                    
                i++;
            }
            
            this.getLigne().setSegments(segments);
            
            try {
                Ligne.dir.enregistrerObjet(
                    this.getLigne(),
                    this.getLigne().getNom()
                );
            } catch (Exception ex) {
                System.err.println(
                    "Impossible d'enregistrer la ligne: " + ex.getMessage()
                );
            }
            
            this.dispose();
        } else {
            if (this._distances.size() == this._arrets.size() - 2) {
                // Avant-dernier arret
                this.butArretSuivant.setText("Confirmer");
                
                
            } else if (this._distances.size() < this._arrets.size() - 1) {
                // Arrets intermédiares
                this.butArretSuivant.setText("Suivant");
            }
        
            DefaultTreeModel mTree = (DefaultTreeModel) this.treeArrets.getModel();
            DefaultMutableTreeNode rootNode = (DefaultMutableTreeNode) mTree.getRoot();

            DefaultMutableTreeNode arretNode = new DefaultMutableTreeNode(
                    this._arrets.get(this._distances.size() - 1)
                    + " - " +
                    this._arrets.get(this._distances.size())
            );
            DefaultMutableTreeNode distanceNode = new DefaultMutableTreeNode(
                    this._distances.getLast().toString()
            );
            arretNode.add(distanceNode);
            rootNode.add(arretNode);
            
            mTree.reload();
            
            this.labelArret1.setText(this._arrets.get(this._distances.size()));
            this.labelArret2.setText(this._arrets.get(this._distances.size() + 1));
        }
    }//GEN-LAST:event_butArretSuivantActionPerformed
    
    private void textDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDistanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDistanceActionPerformed

    private void butAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAjouterActionPerformed
        String nom = this.textNomArret.getText();
        if (this._arrets.contains(nom)) 
            this.labelErreur.setText("Ce nom d'arret existe déjà");
        else {
            this._arrets.add(nom);
        
            Object[] objs = new Object[] { nom };
            DefaultTableModel mTable = (DefaultTableModel) this.tableArrets.getModel();
            mTable.addRow(objs);
        
            DefaultComboBoxModel mCombo = (DefaultComboBoxModel) this.comboArrets.getModel();
            mCombo.addElement(nom);
        }
    }//GEN-LAST:event_butAjouterActionPerformed

    private void butCreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCreerActionPerformed
        try {
            String nom = this.textNumLigne.getText();
            
            if (Ligne.dir.objetExistant(nom)) {
                this.setError("Cette ligne existe déjà");
            } else {
                this._ligne = new Ligne(
                        Integer.parseInt(nom),
                        nom,
                        null
                );
            
                this.setEtape2Enabled(true);
            }
        } catch (Exception e) {
            this.setError("Numero de ligne non valide");
        }
    }//GEN-LAST:event_butCreerActionPerformed
    
    private void setError(String error)
    {
        this.labelErreur.setText(error);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                NouvelleLigne nl = new NouvelleLigne(null, false);
                nl.setVisible(true);
                
                //System.out.println("Ligne recue: "+ nl.getLigne().getNumero());
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAjouter;
    private javax.swing.JButton butArretSuivant;
    private javax.swing.JButton butConfirmerArrets;
    private javax.swing.JButton butCreer;
    private javax.swing.JButton butSupprimerArret;
    private javax.swing.JComboBox comboArrets;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel labelA;
    private javax.swing.JLabel labelArret1;
    private javax.swing.JLabel labelArret2;
    private javax.swing.JLabel labelDe;
    private javax.swing.JLabel labelDistance;
    private javax.swing.JLabel labelErreur;
    private javax.swing.JLabel labelEtape1;
    private javax.swing.JLabel labelEtape2;
    private javax.swing.JLabel labelEtape3;
    private javax.swing.JLabel labelNouvelArret;
    private javax.swing.JLabel labelNumLigne;
    private javax.swing.JLabel labelSupprimerArret;
    private javax.swing.JTable tableArrets;
    private javax.swing.JTextField textDistance;
    private javax.swing.JTextField textNomArret;
    private javax.swing.JTextField textNumLigne;
    private javax.swing.JTree treeArrets;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the _ligne
     */
    public Ligne getLigne() {
        return _ligne;
    }
}
