DROP TABLE pays CASCADE CONSTRAINTS;
DROP TABLE clients CASCADE CONSTRAINTS;
DROP TABLE villages CASCADE CONSTRAINTS;
DROP TABLE sejours CASCADE CONSTRAINTS;
DROP TABLE stages CASCADE CONSTRAINTS;

CREATE TABLE pays (
	codepays CHAR(3) CONSTRAINT PK_PAYS PRIMARY KEY,
	nom VARCHAR2(30)
		CONSTRAINT NN_PAYS_NOM NOT NULL,
	devise VARCHAR2(20) DEFAULT 'euro'
		CONSTRAINT NN_PAYS_DEVISE NOT NULL
);

CREATE TABLE clients (
	idclient NUMBER
		CONSTRAINT PK_CLIENTS PRIMARY KEY,
	nom VARCHAR2(20)
		CONSTRAINT NN_CLIENTS_NOM NOT NULL,
	prenom VARCHAR2(20),
	ville VARCHAR2(20)
		CONSTRAINT NN_CLIENTS_VILLE NOT NULL,
	codepays CHAR(3)
		CONSTRAINT NN_CLIENTS_CODEPAYS NOT NULL
		CONSTRAINT FK_CLIENTS_PAYS
			REFERENCES pays(codepays),
	solde NUMBER DEFAULT 0,
	CONSTRAINT UK_CLIENTS_NOM_PRENOM UNIQUE (prenom, nom)
);

CREATE TABLE villages (
	village VARCHAR2(20)
		CONSTRAINT PK_VILLAGES PRIMARY KEY,
	nbchambres NUMBER DEFAULT 0
		CONSTRAINT CK_VILLAGES_NBCHAMBRES
			CHECK (nbchambres >= 0)
		CONSTRAINT NN_VILLAGES_NBCHAMBRES NOT NULL,
	codepays CHAR(3)
		CONSTRAINT NN_VILLAGES_CODEPAYS NOT NULL
		CONSTRAINT FK_VILLAGES_PAYS
			 REFERENCES pays(codepays),
	tarifmin NUMBER DEFAULT 0
		CONSTRAINT CK_VILLAGES_TARIFMIN
			CHECK (tarifmin >= 0)
		CONSTRAINT NN_VILLAGES_TARIFMIN NOT NULL,
	tarifmax NUMBER DEFAULT 0
		CONSTRAINT CK_VILLAGES_TARIFMAX
			CHECK (tarifmax >= 0)
		CONSTRAINT NN_VILLAGES_TARIFMAX NOT NULL,
	tridents NUMBER DEFAULT 1
		CONSTRAINT CK_VILLAGES_TRIDENTS
			CHECK (tridents BETWEEN 1 AND 4)
		CONSTRAINT NN_TRIDENT NOT NULL,
	CONSTRAINT CK_VILLAGES_TARIFMIN_TARIFMAX
		CHECK (tarifmin <= tarifmax)
);

CREATE TABLE sejours (
	idclient NUMBER,
	village VARCHAR(20),
	datedebut DATE,
	datefin DATE,
	nbpersonnes NUMBER
		CONSTRAINT NN_SEJOURS_NBPERSONNES NOT NULL,
	CONSTRAINT PK_SEJOURS
		PRIMARY KEY (idclient, village, datedebut),
	CONSTRAINT CK_SEJOURS_DATEDEBUT_DATEFIN
		CHECK (datedebut < datefin)
);

CREATE TABLE stages (
	village VARCHAR2(20)
		CONSTRAINT FK_STAGES_VILLAGES REFERENCES villages(village),
	libelle VARCHAR2(30),
	niveau VARCHAR2(25),
	prix NUMBER
		DEFAULT 0,
	CONSTRAINT PK_STAGES
		PRIMARY KEY (village, libelle, niveau)
);
