-- Crée le schéma PATIENT-MEDECIN

CREATE TABLE MEDECIN (
	NumMedecin CHAR(6)
		CONSTRAINT PK_MEDECIN PRIMARY KEY,
	Email VARCHAR2(20),
	DateDiplome DATE
		CONSTRAINT NN_DATEDIPLOME NOT NULL,
	Specialite CHAR(3)
		CONSTRAINT NN_MEDECIN_SPECIALITE NOT NULL
		CONSTRAINT CK_MEDECIN_SPECIALITE
		CHECK (Specialite IN ('112', '145', '678')),
	NumPatient CHAR(5)
		CONSTRAINT NN_MEDECIN_NUMPATIENT NOT NULL,
	CONSTRAINT CK_MEDECIN_NUMMEDECIN CHECK (
		SUBSTR(NumMedecin, 0, 4)
		= TO_CHAR(DateDiplome, 'YYMM')
	)
);

CREATE TABLE PATIENT (
	NumPatient CHAR(5)
		CONSTRAINT PK_PATIENT PRIMARY KEY, 
	NomPatient VARCHAR2(20)
		CONSTRAINT NN_PATIENT_NOMPATIENT NOT NULL,
	Mutuelle NUMBER(3),
	Generaliste CHAR(6)
		CONSTRAINT NN_PATIENT_GENERALISTE NOT NULL
		CONSTRAINT FK_PATIENT_MEDECIN REFERENCES
			MEDECIN(NumMedecin),
	CONSTRAINT CK_PATIENT_NUMPATIENT CHECK (
		UPPER(SUBSTR(NumPatient, 0, 2))
		= UPPER(SUBSTR(NomPatient, 0, 2))
	)
);

ALTER TABLE MEDECIN ADD CONSTRAINT FK_MEDECIN_PATIENT
	FOREIGN KEY (NumPatient) REFERENCES PATIENT(NumPatient);
