--------------------------------------------------------
--  Fichier créé - mardi-mars-01-2011   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ETUDIANTS
--------------------------------------------------------

  CREATE TABLE "JAVAUXRA"."ETUDIANTS" 
   (	"MATRICULE" VARCHAR2(13 CHAR), 
	"NOM" VARCHAR2(50 CHAR), 
	"PRENOM" VARCHAR2(30 CHAR), 
	"NATIONALITE" VARCHAR2(3 CHAR), 
	"ETATCIVIL" CHAR(1 BYTE), 
	"SEXE" CHAR(1 BYTE), 
	"SITUATION" CHAR(1 BYTE), 
	"DATEENTREE" DATE, 
	"DATENAISSANCE" DATE, 
	"LIEUNAISSANCE" VARCHAR2(50 CHAR), 
	"CODEPAYSNAISSANCE" VARCHAR2(3 CHAR), 
	"DATEDECES" DATE, 
	"CODEPOSTALDOM" VARCHAR2(10 CHAR), 
	"LOCALITEDOM" VARCHAR2(50 CHAR), 
	"CODEPAYSDOM" VARCHAR2(3 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PARCOURS_HE
--------------------------------------------------------

  CREATE TABLE "JAVAUXRA"."PARCOURS_HE" 
   (	"MATRICULE" VARCHAR2(13 CHAR), 
	"ANSCO" VARCHAR2(4 CHAR), 
	"ANNETUD" NUMBER(1,0), 
	"REFFORMDET" VARCHAR2(16 CHAR), 
	"REFIMPLAN" VARCHAR2(10 CHAR), 
	"DATEINSCRIPTION" DATE, 
	"REFGROUPE" VARCHAR2(32 CHAR), 
	"DATESORTIE" DATE, 
	"RESULTAT" VARCHAR2(5 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PARCOURS_HE_SESS
--------------------------------------------------------

  CREATE TABLE "JAVAUXRA"."PARCOURS_HE_SESS" 
   (	"MATRICULE" VARCHAR2(13 CHAR), 
	"ANSCO" VARCHAR2(4 CHAR), 
	"SESS" NUMBER(1,0), 
	"TOTAL" NUMBER(3,0), 
	"MENTION" VARCHAR2(4 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Synonymn DBMS_OUTPUT
--------------------------------------------------------

  CREATE OR REPLACE PUBLIC SYNONYM "DBMS_OUTPUT" FOR "SYS"."DBMS_OUTPUT";
--------------------------------------------------------
--  DDL for Function RECHERCHER
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "JAVAUXRA"."RECHERCHER" (
  ANSCO PARCOURS_HE.ANSCO%TYPE DEFAULT 2009,
  ANNETUD PARCOURS_HE.ANNETUD%TYPE DEFAULT 1
  )
  RETURN ETUDIANTS.MATRICULE%TYPE
AS
  matricule ETUDIANTS.MATRICULE%TYPE := NULL;

  AnnetudException EXCEPTION;
  AnscoException EXCEPTION;
BEGIN
  IF Rechercher.ANSCO > EXTRACT (YEAR FROM CURRENT_DATE) THEN
    RAISE AnscoException;
  END IF;
  IF Rechercher.ANNETUD NOT IN (1,2,3) THEN
    RAISE AnnetudException;
  END IF;
  
  SELECT E.MATRICULE INTO matricule
  FROM PARCOURS_HE P
  INNER JOIN ETUDIANTS E
    ON P.MATRICULE = E.MATRICULE
  INNER JOIN PARCOURS_HE_SESS PS
    ON PS.ANSCO = P.ANSCO
    AND PS.MATRICULE = E.MATRICULE
  WHERE P.REFFORMDET = 'ECO-INF0'
    AND P.ANSCO = COALESCE (Rechercher.ANSCO, '2009')
    AND P.ANNETUD = COALESCE (Rechercher.ANNETUD, 1)
    AND PS.TOTAL >= ALL (SELECT PS.TOTAL
      FROM PARCOURS_HE P
      INNER JOIN PARCOURS_HE_SESS PS
	ON PS.ANSCO = P.ANSCO
      WHERE P.REFFORMDET = 'ECO-INF0'
	AND P.ANSCO = COALESCE (Rechercher.ANSCO, '2009')
	AND P.ANNETUD = COALESCE (Rechercher.ANNETUD, 1)
    )
  ;
  
  return matricule;

EXCEPTION
  WHEN AnscoException THEN DBMS_OUTPUT.PUT_LINE('L''année scolaire est dans le futur');
  WHEN AnnetudException THEN DBMS_OUTPUT.PUT_LINE('L''année d''etude ne peut etre que 1, 2 ou 3');
  WHEN NO_DATA_FOUND THEN DBMS_OUTPUT.PUT_LINE('Pas de données correspondante');
  WHEN TOO_MANY_ROWS THEN DBMS_OUTPUT.PUT_LINE('Trop de résultats');
END;

/

