######################################################################
# Automatically generated by qmake (1.07a) Tue Oct 19 09:11:50 2010
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
INTERFACES += BorneReservation.ui
SOURCES += Main.cpp
