CXXCOMPILER=g++

all:	 dossierOctobre.bin

dossierOctobre.bin:	main.cpp LinkedFile.cpp FileIterator.cpp Element.cpp LinkedFile.h FileIterator.h Element.h
	${CXXCOMPILER} -o dossierOctobre.bin main.cpp LinkedFile.cpp FileIterator.cpp Element.cpp
