SELECT EXTRACT (MONTH FROM P.DATEINSCRIPTION), COUNT(E.MATRICULE)
FROM PARCOURS_HE P
INNER JOIN ETUDIANTS E
  ON E.MATRICULE = P.MATRICULE
WHERE P.ANSCO = 2007
GROUP BY EXTRACT (MONTH FROM P.DATEINSCRIPTION)
HAVING COUNT(E.MATRICULE) >=ALL(
	SELECT COUNT(E.MATRICULE)
	FROM PARCOURS_HE P
	INNER JOIN ETUDIANTS E
		ON E.MATRICULE = P.MATRICULE
	WHERE EXTRACT (YEAR FROM P.DATEINSCRIPTION) = 2007
	GROUP BY EXTRACT (MONTH FROM P.DATEINSCRIPTION)
	);