SELECT E.MATRICULE
FROM ETUDIANTS E
WHERE MATRICULE NOT IN (SELECT MATRICULE
	FROM PARCOURS_HE);

SELECT E.MATRICULE
FROM ETUDIANTS E
WHERE NOT EXISTS (SELECT *
	FROM PARCOURS_HE P
	WHERE P.MATRICULE = E.MATRICULE);

SELECT E.MATRICULE
FROM ETUDIANTS E
LEFT JOIN PARCOUTS_HE P
	USING (MATRICULE)
GROUP BY E.MATRICULE
HAVING COUNT(P.MATRICULE) = 0;

SELECT E.MATRICULE
FROM ETUDIANTS E
WHERE NOT EXISTS (SELECT *
	FROM PARCOURS_HE P
	WHERE P.MATRICULE = E.MATRICULE);
