SELECT e.NOM, e.PRENOM
FROM ETUDIANTS e
INNER JOIN PARCOURS_HE p
  ON p.MATRICULE = e.MATRICULE
INNER JOIN FORMATIONS_DET fd
  ON FD.REFFORMDET = P.REFFORMDET
INNER JOIN FORMATIONS f
  ON F.REFFORMATION = fd.refformation
WHERE f.FORMATION = 'Informatique de gestion'
  AND p.ANSCO = 2007
ORDER BY NOM, PRENOM
