SELECT E.NOM, E.PRENOM
FROM PARCOURS_HE P
INNER JOIN ETUDIANTS E
  USING (MATRICULE)
INNER JOIN PARCOURS_HE_SESS PS
  USING (MATRICULE, ANSCO)
WHERE P.RESULTAT = 'R60'
  AND P.ANNETUD = 3
  AND P.ANSCO = 2007
  AND EXISTS (SELECT *
    FROM PARCOURS_HE_SESS
    WHERE MATRICULE = E.MATRICULE
      AND MENTION IN ('DIS', 'GRD', 'PGD')
  )