SELECT E.NOM, E.PRENOM
FROM ETUIDIANTS E
INNER JOIN PARCOURS_HE P
	USING (MATRICULE)
WHERE P.REFFORMDET = 'ECO-INF0'
  AND P.ANSCO = 2007
  AND P.ANNETUD = 3
  AND NOT EXISTS (SELECT *
	FROM PARCOURS_HE_SESS
	WHERE MATRICULE = E.MATRICULE
	  AND SESS = 2);
