UPDATE PARCOURS_HE
SET REFGROUPE = (SELECT REFGROUPE
         FROM GROUPES
         GROUP BY REFGROUPE
	 WHERE REFFORMDET = 'TECH-INS'
         HAVING COUNT(*) >= (SELECT COUNT(*)
		FROM GROUPES
		WHERE REFFORMDET = 'TECH-INS'
                GROUP BY REFGROUPE) 
WHERE MATRICULE = (SELECT MATRICULE
	FROM ETUDIANTS
	WHERE NOM = 'Noel'
	  AND PRENOM = 'Quentin')
  AND ANSCO = 2007
  AND ANNETUD = 2;

SELECT * FROM PARCOURS_HE
WHERE MATRICULE = (SELECT MATRICULE
        FROM ETUDIANTS
        WHERE NOM = 'Noel'
          AND PRENOM = 'Quentin')
  AND ANSCO = 2007
  AND ANNETUD = 2;
