SELECT P.REFGROUPE
FROM PARCOURS_HE P
INNER JOIN ETUDIANTS E
  USING (MATRICULE)
WHERE E.ANSCO = 2007
  AND P.ANNETUD = 3
  AND EXISTS(SELECT *
    FROM PARCOURS_HE P2
    INNER JOIN ETUDIANTS E2
      USING (MATRICULE)
    WHERE E2.SEXE = 'F'
      AND P2.REFGROUPE = P.REFGROUPE
      AND P2.ANSCO = 2007
      AND P2.ANNETUD = 3)
  AND EXISTS(SELECT *
    FROM PARCOURS_HE P2
    INNER JOIN ETUDIANTS E2
      USING (MATRICULE)
    WHERE E2.SEXE = 'M'
      AND P2.REFGROUPE = P.REFGROUPE
      AND P2.ANSCO = 2007
      AND P2.ANNETUD = 3)
GROUP BY P.REFGROUPE

SELECT P.REFGROUPE
FROM PARCOURS_HE P
WHERE E.ANSCO = 2007
  AND P.ANNETUD = 3
  AND P.REFGROUPE IN (SELECT DISTINCT P.REFGROUPE
    FROM PARCOURS_HE P
    INNER JOIN ETUDIANTS E
      USING (MATRICULE)
    WHERE E.SEXE = 'F'
      AND P.ANSCO = 2007
      AND P.ANNETUD = 3)
  AND P.REFGROUPE IN (SELECT DISTINCT P.REFGROUPE
    FROM PARCOURS_HE P
    INNER JOIN ETUDIANTS E
      USING (MATRICULE)
    WHERE E.SEXE = 'M'
      AND P.ANSCO = 2007
      AND P.ANNETUD = 3)

SELECT DISTINCT P.REFGROUPE
FROM PARCOURS_HE P
INNER JOIN ETUDIANTS E
  USING (MATRICULE)
WHERE E.SEXE = 'F'
  AND P.ANSCO = 2007
  AND P.ANNETUD = 3
INTERSECT
SELECT DISTINCT P.REFGROUPE
FROM PARCOURS_HE P
INNER JOIN ETUDIANTS E
  USING (MATRICULE)
WHERE E.SEXE = 'M'
  AND P.ANSCO = 2007
  AND P.ANNETUD = 3

SELECT P.REFGROUPE
FROM PARCOURS_HE P
INNER JOIN ETUDIANTS E1
  ON E1.MATRICULE = P.MATRICULE
  AND E1.SEXE = 'F'
INNER JOIN ETUDIANTS E2
  ON E2.MATRICULE = P.MATRICULE
  AND E2.SEXE = 'M'
WHERE P.ANSCO = 2007
  AND P.ANNETUD = 3
GROUP BY P.REFGROUPE