SELECT REFGROUPE
FROM GROUPES
WHERE ANNETUD = 2
  AND REFFORMDET = 'ECO-INF0'
  AND ANSCO = 2005
INTERSECT
SELECT REFGROUPE
FROM GROUPES
WHERE ANNETUD = 2
  AND REFFORMDET = 'ECO-INF0'
  AND ANSCO = 2006;
