SELECT REFGROUPE
FROM GROUPES G1
WHERE ANNETUD = 2
  AND REFFORMDET = 'ECO-INF0'
  AND ANSCO = 2005
  AND EXISTS (SELECT *
	FROM GROUPES G2
	WHERE ANNETUD = 2
	  AND REFFORMDET = 'ECO-INF0'
	  AND ANSCO = 2006
	  AND G1.REFGROUPE = G2.REFGROUPE);

