SELECT DISTINCT REFGROUPE
FROM GROUPES
WHERE ANNETUD = 2
  AND REFFORMDET = 'ECO-INF0'
  AND ANSCO <= 2007
  AND REFGROUPE NOT IN (SELECT DISTINCT REFGROUPE
	FROM GROUPES 
	WHERE ANNETUD = 2
	  AND REFFORMDET = 'ECO-INF0'
	  AND ANSCO > 2007);
