SELECT DISTINCT G1.REFGROUPE
FROM GROUPES G1
LEFT JOIN GROUPES G2
        ON G1.REFGROUPE = G2.REFGROUPE
        AND G1.REFFORMDET = G2.REFFORMDET
        AND G1.ANNETUD = G2.ANNETUD
        AND G1.REFIMPLAN = G2.REFIMPLAN
	AND G2.ANSCO > 2007
WHERE G1.ANNETUD = 2
  AND G1.REFFORMDET = 'ECO-INF0'
  AND G1.ANSCO <= 2007
  AND G2.REFGROUPE IS NULL;
