CREATE VIEW V_ETUDIANTS_GROUPE
  AS SELECT E.*
  FROM ETUDIANTS E
  INNER JOIN PARCOURS_HE P
    ON E.MATRICULE = P.MATRICULE
  WHERE P.ANSCO = 2009
  AND P.REFGROUPE = (SELECT P.REFGROUPE
    FROM ETUDIANTS E
    INNER JOIN PARCOURS_HE P
      ON E.MATRICULE = P.MATRICULE
    WHERE P.ANSCO = 2009
    AND UPPER(E.NOM || SUBSTR(E.PRENOM, 0, 2)) = USER);
