CREATE VIEW V_GROUPES_COMMUNE AS
  SELECT P.REFGROUPE, COUNT(P.REFGROUPE) AS NBRE_ETUDS
  FROM ETUDIANTS E
  INNER JOIN PARCOURS_HE P
    ON E.MATRICULE = P.MATRICULE
  WHERE P.ANSCO = 2009
  AND E.LOCALITEDOM = (SELECT E.LOCALITEDOM
    FROM ETUDIANTS E
    WHERE UPPER(E.NOM || SUBSTR(E.PRENOM, 0, 2)) = USER)
  GROUP BY P.REFGROUPE;
